name: solid_color_generator
description: "Solid color generator."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  solid_lints: ^0.1.5

flutter:
  uses-material-design: true
